### ISSUE TITLE
Suggestion to your translation

### ISSUE THREAD

**Issue by JaeYeopHan** [SoYoung210/SOSOLOG#3]
#### 1.

`constructor` 를 정의하고, `super(props` 를 정의하는 것은
=> `constructor` 를 정의하고, `super(props)` 를 정의하는 것은

#### 2.

~할 것이다. ~할 것입니다. 두 가지 어투를 통일시키는건 어떨까요?

#### 3.

의역한 부분에 대해서는 영어 원문을 노출시키는 것도 좋아보입니다~

**Comment by JaeYeopHan** [comment]
If you've applied this review, you can close this issue.

**Comment by SoYoung210** [comment]
다음 배포와 함께 close 하겠습니다!😀
